// gt-frontend/src/components/AppConfirm.vue
<script setup>
import { useConfirmStore } from '@/stores/confirm.store'

const confirm = useConfirmStore()
</script>

<template>
  <v-dialog
    :model-value="confirm.open"
    max-width="380"
    @update:model-value="v => !v && confirm.settle(false)"
  >
    <v-card class="dlg-card">
      <v-card-title class="dlg-title">{{ confirm.title }}</v-card-title>
      <v-card-text v-if="confirm.message" class="dlg-msg">
        {{ confirm.message }}
      </v-card-text>
      <v-card-actions class="dlg-actions">
        <v-btn variant="outlined" class="btn-ghost" @click="confirm.settle(false)">
          {{ confirm.cancelLabel }}
        </v-btn>
        <button
          type="button"
          :class="confirm.danger ? 'btn-danger' : 'btn-gradient'"
          @click="confirm.settle(true)"
        >
          {{ confirm.confirmLabel }}
        </button>
      </v-card-actions>
    </v-card>
  </v-dialog>
</template>

<style scoped lang="scss">
.dlg-card {
  background: $surface !important;
  border: 1px solid $stroke;
  border-radius: $radius !important;
}

.dlg-title {
  font-family: 'Space Grotesk', sans-serif;
  font-weight: 600;
  color: $text;
}

.dlg-msg {
  padding-top: 4px !important;
  font-size: 0.9rem;
  line-height: 1.45;
  color: $muted;
}

.dlg-actions {
  padding: 8px 16px 16px;
  gap: 8px;
  justify-content: flex-end;
}

.btn-ghost {
  border-color: $stroke !important;
  color: $muted !important;
  text-transform: none;
}

.btn-gradient,
.btn-danger {
  min-width: 88px;
  height: 40px;
  padding: 0 20px;
  border: none;
  border-radius: $radius-btn;
  color: #fff;
  font-family: 'Space Grotesk', sans-serif;
  font-weight: 600;
  cursor: pointer;

  &:active {
    transform: scale(0.97);
  }
}

.btn-gradient {
  background: $gradient;
}

.btn-danger {
  background: $red;
}
</style>

// gt-frontend-react/src/features/ui/AppConfirm.jsx
import {
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Button,
  Typography,
} from '@mui/material'
import { useAppDispatch, useAppSelector } from '@/app/hooks'
import { selectConfirm } from './uiSlice'
import { settleConfirm } from './uiThunks'
import { colors } from '@/app/theme'

export default function AppConfirm() {
  const dispatch = useAppDispatch()
  const c = useAppSelector(selectConfirm)

  return (
    <Dialog
      open={c.open}
      onClose={() => dispatch(settleConfirm(false))}
      maxWidth="xs"
      fullWidth
      slotProps={{
        paper: {
          sx: {
            bgcolor: colors.surface,
            border: `1px solid ${colors.stroke}`,
            borderRadius: colors.radius,
          },
        },
      }}
    >
      <DialogTitle
        sx={{ fontFamily: "'Space Grotesk', sans-serif", fontWeight: 600, color: colors.text }}
      >
        {c.title}
      </DialogTitle>
      {c.message ? (
        <DialogContent>
          <Typography sx={{ fontSize: '0.9rem', lineHeight: 1.45, color: colors.muted }}>
            {c.message}
          </Typography>
        </DialogContent>
      ) : null}
      <DialogActions sx={{ px: 2, pb: 2, gap: 1 }}>
        <Button
          variant="outlined"
          onClick={() => dispatch(settleConfirm(false))}
          sx={{ borderColor: colors.stroke, color: colors.muted }}
        >
          {c.cancelLabel}
        </Button>
        <Button
          variant="contained"
          onClick={() => dispatch(settleConfirm(true))}
          sx={{
            minWidth: 88,
            bgcolor: c.danger ? colors.red : undefined,
            background: c.danger ? colors.red : colors.gradient,
            color: '#fff',
            '&:hover': {
              bgcolor: c.danger ? colors.red : undefined,
              filter: 'brightness(1.08)',
            },
          }}
        >
          {c.confirmLabel}
        </Button>
      </DialogActions>
    </Dialog>
  )
}
