// gt-frontend/src/components/AppLoader.vue
<script setup>
import { onUnmounted, ref, watch } from 'vue'
import { useLoaderStore } from '@/stores/loader.store'

const loader = useLoaderStore()

const icons = [
  'mdi-dumbbell',
  'mdi-weight-lifter',
  'mdi-kettlebell',
]

const index = ref(0)
let timer

function startCycle() {
  stopCycle()
  index.value = 0
  timer = setInterval(() => {
    index.value = (index.value + 1) % icons.length
  }, 900)
}

function stopCycle() {
  if (timer) {
    clearInterval(timer)
    timer = undefined
  }
}

watch(
  () => loader.active,
  (active) => {
    if (active) startCycle()
    else stopCycle()
  },
  { immediate: true },
)

onUnmounted(stopCycle)
</script>

<template>
  <div
    v-if="loader.active"
    class="app-loader"
    role="status"
    aria-live="polite"
    aria-label="Loading"
  >
    <div class="backdrop" />
    <div class="stage">
      <div class="pulse" aria-hidden="true" />
      <div class="icon-wrap">
        <Transition name="equip" mode="out-in">
          <v-icon
            :key="icons[index]"
            :icon="icons[index]"
            size="36"
            class="equip-icon"
          />
        </Transition>
      </div>
    </div>
  </div>
</template>

<style scoped lang="scss">
.app-loader {
  position: fixed;
  inset: 0;
  z-index: 9999;
  display: grid;
  place-items: center;
  pointer-events: all;
}

.backdrop {
  position: absolute;
  inset: 0;
  background: rgba($bg, 0.72);
  backdrop-filter: blur(4px);
}

.stage {
  position: relative;
  z-index: 1;
  width: 88px;
  height: 88px;
  display: grid;
  place-items: center;
  border-radius: 50%;
  background:
    linear-gradient($surface, $surface) padding-box,
    $gradient border-box;
  border: 2px solid transparent;
  overflow: hidden;
}

.pulse {
  position: absolute;
  inset: 0;
  border-radius: 50%;
  background: radial-gradient(circle, rgba($blue, 0.35) 0%, rgba($blue, 0.08) 55%, transparent 70%);
  animation: pulse-ring 1.6s ease-in-out infinite;
}

.icon-wrap {
  position: relative;
  z-index: 1;
  width: 44px;
  height: 44px;
  display: grid;
  place-items: center;
}

.equip-icon {
  color: $text !important;
  filter: drop-shadow(0 0 10px rgba($blue, 0.35));
}

.equip-enter-active,
.equip-leave-active {
  transition: opacity 0.25s ease, transform 0.25s ease;
}

.equip-enter-from {
  opacity: 0;
  transform: scale(0.7) translateY(6px);
}

.equip-leave-to {
  opacity: 0;
  transform: scale(0.7) translateY(-6px);
}

@keyframes pulse-ring {
  0%,
  100% {
    transform: scale(0.88);
    opacity: 0.7;
  }
  50% {
    transform: scale(1.12);
    opacity: 1;
  }
}
</style>

// gt-frontend-react/src/features/ui/AppLoader.jsx
import { useEffect, useState } from 'react'
import FitnessCenterIcon from '@mui/icons-material/FitnessCenter'
import SportsGymnasticsIcon from '@mui/icons-material/SportsGymnastics'
import { Box } from '@mui/material'
import { useAppSelector } from '@/app/hooks'
import { selectLoaderActive } from './uiSlice'
import { colors } from '@/app/theme'

const ICONS = [FitnessCenterIcon, SportsGymnasticsIcon, FitnessCenterIcon]

export default function AppLoader() {
  const active = useAppSelector(selectLoaderActive)
  const [index, setIndex] = useState(0)

  useEffect(() => {
    if (!active) return undefined
    const timer = setInterval(() => {
      setIndex(i => (i + 1) % ICONS.length)
    }, 900)
    return () => {
      clearInterval(timer)
      setIndex(0)
    }
  }, [active])

  if (!active) return null

  const Icon = ICONS[index]

  return (
    <Box
      role="status"
      aria-live="polite"
      aria-label="Loading"
      sx={{
        position: 'fixed',
        inset: 0,
        zIndex: 9999,
        display: 'grid',
        placeItems: 'center',
        pointerEvents: 'all',
      }}
    >
      <Box
        sx={{
          position: 'absolute',
          inset: 0,
          bgcolor: 'rgba(10, 12, 17, 0.72)',
          backdropFilter: 'blur(4px)',
        }}
      />
      <Box
        sx={{
          position: 'relative',
          zIndex: 1,
          width: 88,
          height: 88,
          display: 'grid',
          placeItems: 'center',
          borderRadius: '50%',
          background: `linear-gradient(${colors.surface}, ${colors.surface}) padding-box, ${colors.gradient} border-box`,
          border: '2px solid transparent',
          overflow: 'hidden',
          '&::before': {
            content: '""',
            position: 'absolute',
            inset: 0,
            borderRadius: '50%',
            background:
              'radial-gradient(circle, rgba(59, 130, 246, 0.35) 0%, rgba(59, 130, 246, 0.08) 55%, transparent 70%)',
            animation: 'pulse-ring 1.6s ease-in-out infinite',
          },
          '@keyframes pulse-ring': {
            '0%, 100%': { transform: 'scale(0.88)', opacity: 0.7 },
            '50%': { transform: 'scale(1.12)', opacity: 1 },
          },
        }}
      >
        <Icon
          sx={{
            position: 'relative',
            zIndex: 1,
            fontSize: 36,
            color: colors.text,
            filter: 'drop-shadow(0 0 10px rgba(59, 130, 246, 0.35))',
          }}
        />
      </Box>
    </Box>
  )
}
