// gt-frontend-react/src/features/ui/AppSnackbar.jsx
import { Snackbar, Alert, IconButton } from '@mui/material'
import CloseIcon from '@mui/icons-material/Close'
import CheckCircleOutlineIcon from '@mui/icons-material/CheckCircleOutlined'
import ErrorOutlineIcon from '@mui/icons-material/ErrorOutlined'
import WarningAmberIcon from '@mui/icons-material/WarningAmber'
import InfoOutlinedIcon from '@mui/icons-material/InfoOutlined'
import { useAppDispatch, useAppSelector } from '@/app/hooks'
import { snackbarClosed, selectSnackbar } from './uiSlice'
import { colors } from '@/app/theme'

const ICONS = {
  success: CheckCircleOutlineIcon,
  error: ErrorOutlineIcon,
  warning: WarningAmberIcon,
  info: InfoOutlinedIcon,
}

const BORDERS = {
  success: 'rgba(52, 211, 153, 0.45)',
  error: 'rgba(239, 68, 68, 0.5)',
  warning: 'rgba(245, 158, 11, 0.5)',
  info: 'rgba(59, 130, 246, 0.45)',
}

const ICON_COLORS = {
  success: colors.success,
  error: colors.red,
  warning: colors.warning,
  info: colors.blue,
}

export default function AppSnackbar() {
  const dispatch = useAppDispatch()
  const snackbar = useAppSelector(selectSnackbar)
  const Icon = ICONS[snackbar.type] || ICONS.info

  return (
    <Snackbar
      key={snackbar.key}
      open={snackbar.open}
      autoHideDuration={snackbar.timeout}
      onClose={(_, reason) => {
        if (reason !== 'clickaway') dispatch(snackbarClosed())
      }}
      anchorOrigin={{ vertical: 'top', horizontal: 'right' }}
      sx={{ mt: 1.5, mr: 1.5 }}
    >
      <Alert
        severity={snackbar.type}
        icon={<Icon sx={{ color: ICON_COLORS[snackbar.type] || colors.blue }} />}
        action={
          <IconButton
            size="small"
            aria-label="Close"
            color="inherit"
            onClick={() => dispatch(snackbarClosed())}
          >
            <CloseIcon fontSize="small" />
          </IconButton>
        }
        sx={{
          minWidth: 260,
          maxWidth: 'min(360px, calc(100vw - 24px))',
          bgcolor: colors.surface,
          color: colors.text,
          border: `1px solid ${BORDERS[snackbar.type] || BORDERS.info}`,
          borderRadius: colors.radiusBtn,
          boxShadow: '0 12px 32px rgba(0, 0, 0, 0.45)',
          alignItems: 'flex-start',
          '& .MuiAlert-message': { py: 0.25, fontSize: '0.875rem', lineHeight: 1.4 },
          '& .MuiAlert-icon': { py: 0.5 },
        }}
      >
        {snackbar.message}
      </Alert>
    </Snackbar>
  )
}

// gt-frontend/src/components/AppSnackbar.vue
<script setup>
import { useSnackbarStore } from '@/stores/snackbar.store'

const snack = useSnackbarStore()
</script>

<template>
  <v-snackbar
    v-model="snack.open"
    class="app-snackbar"
    :class="snack.type"
    location="top end"
    :timeout="snack.timeout"
    multi-line
  >
    <div class="body">
      <v-icon :icon="snack.icon" size="20" class="icon" />
      <span>{{ snack.message }}</span>
    </div>
    <template #actions>
      <v-btn icon variant="text" size="small" aria-label="Close" @click="snack.close()">
        <v-icon icon="mdi-close" size="18" />
      </v-btn>
    </template>
  </v-snackbar>
</template>

<style scoped lang="scss">
.app-snackbar {
  :deep(.v-snackbar__wrapper) {
    min-width: 260px;
    max-width: min(360px, calc(100vw - 24px));
    margin: 12px 12px 0 0 !important;
    border-radius: $radius-btn !important;
    border: 1px solid $stroke;
    background: $surface !important;
    color: $text !important;
    box-shadow: 0 12px 32px rgba(0, 0, 0, 0.45);
  }

  &.success :deep(.v-snackbar__wrapper) {
    border-color: rgba(#34d399, 0.45);
    .icon {
      color: #34d399;
    }
  }
  &.error :deep(.v-snackbar__wrapper) {
    border-color: rgba($red, 0.5);
    .icon {
      color: $red;
    }
  }
  &.warning :deep(.v-snackbar__wrapper) {
    border-color: rgba(#f59e0b, 0.5);
    .icon {
      color: #f59e0b;
    }
  }
  &.info :deep(.v-snackbar__wrapper) {
    border-color: rgba($blue, 0.45);
    .icon {
      color: $blue;
    }
  }
}

.body {
  display: flex;
  align-items: flex-start;
  gap: 10px;
  font-size: 0.875rem;
  line-height: 1.4;
  padding-block: 2px;
}

.icon {
  flex-shrink: 0;
  margin-top: 1px;
}
</style>
