// gt-frontend-react/src/features/users/UsersPage.jsx
import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import {
  AppBar,
  Toolbar,
  Box,
  IconButton,
  Typography,
  TextField,
  Menu,
  MenuItem,
  ListItemIcon,
  ListItemText,
  CircularProgress,
  InputAdornment,
} from '@mui/material'
import ArrowBackIcon from '@mui/icons-material/ArrowBack'
import PersonOutlineIcon from '@mui/icons-material/PersonOutlined'
import EmailOutlinedIcon from '@mui/icons-material/EmailOutlined'
import LockOutlinedIcon from '@mui/icons-material/LockOutlined'
import ContentCopyIcon from '@mui/icons-material/ContentCopy'
import SearchIcon from '@mui/icons-material/Search'
import CloseIcon from '@mui/icons-material/Close'
import MoreVertIcon from '@mui/icons-material/MoreVert'
import StarIcon from '@mui/icons-material/Star'
import LockResetIcon from '@mui/icons-material/LockReset'
import PersonOffIcon from '@mui/icons-material/PersonOff'
import PersonIcon from '@mui/icons-material/Person'
import DeleteOutlineIcon from '@mui/icons-material/DeleteOutlined'
import { useAppDispatch, useAppSelector } from '@/app/hooks'
import { colors } from '@/app/theme'
import {
  fetchUsers,
  setUserSearch,
  clearUserSearch,
  createUserAction,
  createFormSet,
  toggleUserStatus,
  resetUserPassword,
  deleteUserAction,
  copyText,
  selectGeneratedEmail,
  DEFAULT_PASSWORD,
} from '@/features/users/usersSlice'

const fieldSx = {
  '& .MuiOutlinedInput-root': {
    borderRadius: colors.radiusBtn,
    bgcolor: colors.surface2,
  },
}

export default function UsersPage() {
  const dispatch = useAppDispatch()
  const navigate = useNavigate()
  const name = useAppSelector(s => s.users.name)
  const password = useAppSelector(s => s.users.password)
  const list = useAppSelector(s => s.users.list)
  const search = useAppSelector(s => s.users.search)
  const searching = useAppSelector(s => s.users.searching)
  const generatedEmail = useAppSelector(selectGeneratedEmail)

  const [menuAnchor, setMenuAnchor] = useState(null)
  const [menuUserId, setMenuUserId] = useState(null)

  useEffect(() => {
    dispatch(fetchUsers())
  }, [dispatch])

  const menuUser = list.find(u => u.id === menuUserId)

  return (
    <Box sx={{ bgcolor: colors.bg, minHeight: '100%' }}>
      <AppBar
        position="static"
        elevation={0}
        sx={{ bgcolor: colors.surface, borderBottom: `1px solid ${colors.stroke}`, height: 56 }}
      >
        <Toolbar sx={{ minHeight: '56px !important' }}>
          <IconButton
            aria-label="Back"
            onClick={() => navigate('/')}
            sx={{ color: colors.text, '&:hover .back-icon': { transform: 'translateX(-3px)' } }}
          >
            <ArrowBackIcon className="back-icon" sx={{ transition: 'transform 0.2s' }} />
          </IconButton>
          <Typography
            variant="h6"
            sx={{
              fontFamily: "'Space Grotesk', sans-serif",
              fontWeight: 600,
              fontSize: '1.05rem',
              color: colors.text,
            }}
          >
            Users
          </Typography>
        </Toolbar>
      </AppBar>

      <Box
        sx={{
          p: 2,
          maxWidth: 480,
          mx: 'auto',
          display: 'flex',
          flexDirection: 'column',
          gap: 1.75,
        }}
      >
        <Box
          sx={{
            p: '20px 16px',
            bgcolor: colors.surface,
            border: `1px solid ${colors.stroke}`,
            borderRadius: colors.radius,
          }}
        >
          <Box
            component="p"
            sx={{
              m: '0 0 14px',
              fontFamily: "'Space Grotesk', sans-serif",
              fontSize: '0.95rem',
              fontWeight: 600,
              color: colors.text,
            }}
          >
            Create user
          </Box>
          <Box sx={{ display: 'flex', flexDirection: 'column', gap: 1.5, mb: 1.75 }}>
            <TextField
              label="Name"
              value={name}
              onChange={e => dispatch(createFormSet({ name: e.target.value }))}
              onKeyDown={e => e.key === 'Enter' && dispatch(createUserAction())}
              slotProps={{
                input: {
                  startAdornment: (
                    <InputAdornment position="start">
                      <PersonOutlineIcon sx={{ color: colors.muted, fontSize: 20 }} />
                    </InputAdornment>
                  ),
                },
              }}
              sx={fieldSx}
            />
            <Box sx={{ position: 'relative' }}>
              <TextField
                label="Email"
                type="email"
                value={generatedEmail}
                disabled
                slotProps={{
                  input: {
                    startAdornment: (
                      <InputAdornment position="start">
                        <EmailOutlinedIcon sx={{ color: colors.muted, fontSize: 20 }} />
                      </InputAdornment>
                    ),
                  },
                }}
                sx={fieldSx}
              />
              <IconButton
                size="small"
                aria-label="Copy email"
                onClick={() =>
                  dispatch(
                    copyText({
                      text: generatedEmail,
                      successMsg: 'Email copied',
                      emptyMsg: 'Enter a name first',
                    })
                  )
                }
                sx={{
                  position: 'absolute',
                  right: 8,
                  top: '50%',
                  transform: 'translateY(-50%)',
                  zIndex: 1,
                }}
              >
                <ContentCopyIcon sx={{ fontSize: 18 }} />
              </IconButton>
            </Box>
            <Box sx={{ position: 'relative' }}>
              <TextField
                label="Password"
                type="text"
                value={password}
                onChange={e => dispatch(createFormSet({ password: e.target.value }))}
                slotProps={{
                  input: {
                    startAdornment: (
                      <InputAdornment position="start">
                        <LockOutlinedIcon sx={{ color: colors.muted, fontSize: 20 }} />
                      </InputAdornment>
                    ),
                  },
                }}
                sx={fieldSx}
              />
              <IconButton
                size="small"
                aria-label="Copy password"
                onClick={() =>
                  dispatch(
                    copyText({
                      text: DEFAULT_PASSWORD,
                      successMsg: 'Default password copied',
                      emptyMsg: '',
                    })
                  )
                }
                sx={{
                  position: 'absolute',
                  right: 8,
                  top: '50%',
                  transform: 'translateY(-50%)',
                  zIndex: 1,
                }}
              >
                <ContentCopyIcon sx={{ fontSize: 18 }} />
              </IconButton>
            </Box>
            <Box
              component="p"
              sx={{ m: '-6px 0 0', fontSize: '0.75rem', lineHeight: 1.3, color: colors.muted }}
            >
              Min 4 characters
            </Box>
          </Box>
          <Box
            component="button"
            type="button"
            onClick={() => dispatch(createUserAction())}
            sx={{
              width: '100%',
              height: 44,
              border: 'none',
              borderRadius: colors.radiusBtn,
              background: colors.gradient,
              color: '#fff',
              fontFamily: "'Space Grotesk', sans-serif",
              fontWeight: 600,
              cursor: 'pointer',
              transition: 'filter 0.15s, transform 0.15s',
              '&:active': { transform: 'scale(0.98)' },
              '&:hover': { filter: 'brightness(1.08)' },
            }}
          >
            Create
          </Box>
        </Box>

        <Box
          sx={{
            p: '20px 16px',
            bgcolor: colors.surface,
            border: `1px solid ${colors.stroke}`,
            borderRadius: colors.radius,
          }}
        >
          <Box
            component="p"
            sx={{
              m: '0 0 14px',
              fontFamily: "'Space Grotesk', sans-serif",
              fontSize: '0.95rem',
              fontWeight: 600,
              color: colors.text,
            }}
          >
            All users
          </Box>
          <TextField
            label="Search users"
            value={search}
            onChange={e => dispatch(setUserSearch(e.target.value))}
            slotProps={{
              input: {
                startAdornment: (
                  <InputAdornment position="start">
                    <SearchIcon sx={{ color: colors.muted, fontSize: 20 }} />
                  </InputAdornment>
                ),
                endAdornment: search ? (
                  <InputAdornment position="end">
                    <IconButton
                      size="small"
                      aria-label="Clear search"
                      onClick={() => dispatch(clearUserSearch())}
                    >
                      <CloseIcon fontSize="small" />
                    </IconButton>
                  </InputAdornment>
                ) : null,
              },
            }}
            sx={{ ...fieldSx, mb: 1.75 }}
          />

          {searching ? (
            <Box
              sx={{
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                minHeight: 72,
                color: colors.blue,
              }}
              aria-live="polite"
              aria-busy="true"
            >
              <CircularProgress size={28} thickness={2} color="primary" />
            </Box>
          ) : (
            <Box
              component="ul"
              sx={{
                listStyle: 'none',
                m: 0,
                p: 0,
                display: 'flex',
                flexDirection: 'column',
                gap: 1.25,
              }}
            >
              {list.map(u => (
                <Box
                  key={u.id}
                  component="li"
                  sx={{
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'space-between',
                    gap: 1.5,
                    p: 1.5,
                    bgcolor: colors.surface2,
                    borderRadius: colors.radiusBtn,
                  }}
                >
                  <Box sx={{ minWidth: 0, flex: 1 }}>
                    <Box
                      component="p"
                      sx={{
                        m: 0,
                        display: 'inline-flex',
                        alignItems: 'center',
                        gap: 0.5,
                        fontFamily: "'Space Grotesk', sans-serif",
                        fontSize: '0.9rem',
                        fontWeight: 600,
                        color: colors.text,
                      }}
                    >
                      {u.name}
                      {u.status === 'disabled' && (
                        <Box
                          component="span"
                          aria-label="Disabled"
                          title="Disabled"
                          sx={{
                            display: 'inline-block',
                            width: 8,
                            height: 8,
                            borderRadius: '50%',
                            bgcolor: colors.red,
                            flexShrink: 0,
                          }}
                        />
                      )}
                      {u.role === 'admin' && (
                        <StarIcon sx={{ fontSize: 16, color: colors.blue }} aria-label="Admin" />
                      )}
                    </Box>
                    <Box sx={{ display: 'flex', alignItems: 'center', gap: 0.25, mt: 0.25 }}>
                      <Box
                        component="p"
                        sx={{
                          m: 0,
                          fontSize: '0.8rem',
                          color: colors.muted,
                          overflow: 'hidden',
                          textOverflow: 'ellipsis',
                          whiteSpace: 'nowrap',
                        }}
                      >
                        {u.email}
                      </Box>
                      <IconButton
                        size="small"
                        aria-label="Copy email"
                        onClick={() =>
                          dispatch(
                            copyText({
                              text: u.email,
                              successMsg: 'Email copied',
                              emptyMsg: '',
                            })
                          )
                        }
                      >
                        <ContentCopyIcon sx={{ fontSize: 16 }} />
                      </IconButton>
                    </Box>
                  </Box>
                  <IconButton
                    size="small"
                    aria-label="User actions"
                    sx={{ flexShrink: 0 }}
                    onClick={e => {
                      setMenuUserId(u.id)
                      setMenuAnchor(e.currentTarget)
                    }}
                  >
                    <MoreVertIcon />
                  </IconButton>
                </Box>
              ))}
            </Box>
          )}
        </Box>
      </Box>

      <Menu
        anchorEl={menuAnchor}
        open={Boolean(menuAnchor)}
        onClose={() => {
          setMenuAnchor(null)
          setMenuUserId(null)
        }}
        anchorOrigin={{ vertical: 'bottom', horizontal: 'right' }}
        transformOrigin={{ vertical: 'top', horizontal: 'right' }}
        slotProps={{ paper: { sx: { minWidth: 160 } } }}
      >
        <MenuItem
          onClick={() => {
            const id = menuUserId
            setMenuAnchor(null)
            if (id) dispatch(resetUserPassword(id))
          }}
        >
          <ListItemIcon>
            <LockResetIcon fontSize="small" />
          </ListItemIcon>
          <ListItemText>Reset password</ListItemText>
        </MenuItem>
        {menuUser && menuUser.role !== 'admin' && (
          <MenuItem
            onClick={() => {
              const id = menuUserId
              setMenuAnchor(null)
              if (id) dispatch(toggleUserStatus(id))
            }}
          >
            <ListItemIcon>
              {menuUser.status === 'active' ? (
                <PersonOffIcon fontSize="small" />
              ) : (
                <PersonIcon fontSize="small" />
              )}
            </ListItemIcon>
            <ListItemText>{menuUser.status === 'active' ? 'Disable' : 'Enable'}</ListItemText>
          </MenuItem>
        )}
        {menuUser && menuUser.role !== 'admin' && (
          <MenuItem
            onClick={() => {
              const id = menuUserId
              setMenuAnchor(null)
              if (id) dispatch(deleteUserAction(id))
            }}
          >
            <ListItemIcon>
              <DeleteOutlineIcon fontSize="small" />
            </ListItemIcon>
            <ListItemText>Delete</ListItemText>
          </MenuItem>
        )}
      </Menu>
    </Box>
  )
}

// gt-frontend/src/pages/users/UsersPage.vue
<script setup>
import { onMounted } from 'vue'
import { useAppStore } from '@/stores/app.store'
import { useUsersStore } from '@/stores/users.store'

const app = useAppStore()
const users = useUsersStore()

onMounted(() => {
  users.fetchList()
})
</script>

<template>
  <div class="users">
    <v-app-bar flat class="bar" height="56">
      <v-btn icon variant="text" aria-label="Back" @click="app.goDashboard()">
        <v-icon icon="mdi-arrow-left" class="back-icon" />
      </v-btn>
      <v-toolbar-title class="title">Users</v-toolbar-title>
    </v-app-bar>

    <div class="content">
      <div class="panel">
        <p class="section">Create user</p>
        <div class="fields">
          <v-text-field
            v-model="users.name"
            label="Name"
            prepend-inner-icon="mdi-account-outline"
            rounded="lg"
            @keyup.enter="users.create()"
          />
          <div class="copy-field">
            <v-text-field
              :model-value="users.generatedEmail"
              label="Email"
              type="email"
              prepend-inner-icon="mdi-email-outline"
              rounded="lg"
              disabled
              hide-details
            />
            <v-btn
              icon
              variant="text"
              size="small"
              class="copy-btn"
              aria-label="Copy email"
              @click="users.copyGeneratedEmail()"
            >
              <v-icon icon="mdi-content-copy" size="18" />
            </v-btn>
          </div>
          <div class="copy-field">
            <v-text-field
              v-model="users.password"
              label="Default password"
              type="text"
              prepend-inner-icon="mdi-lock-outline"
              rounded="lg"
              disabled
              hide-details
            />
            <v-btn
              icon
              variant="text"
              size="small"
              class="copy-btn"
              aria-label="Copy default password"
              @click="users.copyDefaultPassword()"
            >
              <v-icon icon="mdi-content-copy" size="18" />
            </v-btn>
          </div>
        </div>
        <button class="btn-gradient" type="button" @click="users.create()">Create</button>
      </div>

      <div class="panel">
        <p class="section">All users</p>
        <v-text-field
          :model-value="users.search"
          label="Search users"
          prepend-inner-icon="mdi-magnify"
          clearable
          hide-details
          rounded="lg"
          class="search"
          @update:model-value="users.setSearch($event ?? '')"
          @click:clear="users.clearSearch()"
        />
        <div v-if="users.searching" class="list-loader" aria-live="polite" aria-busy="true">
          <v-progress-circular indeterminate size="28" width="2" color="primary" />
        </div>
        <ul v-else class="list">
          <li v-for="u in users.list" :key="u.id" class="row">
            <div class="info">
              <p class="name">
                {{ u.name }}
                <span
                  v-if="u.status === 'disabled'"
                  class="status-dot"
                  aria-label="Disabled"
                  title="Disabled"
                />
                <v-icon
                  v-if="u.role === 'admin'"
                  icon="mdi-star"
                  size="16"
                  class="admin-star"
                  aria-label="Admin"
                />
              </p>
              <div class="email-row">
                <p class="email">{{ u.email }}</p>
                <v-btn
                  icon
                  variant="text"
                  size="x-small"
                  aria-label="Copy email"
                  @click="users.copyEmail(u.email)"
                >
                  <v-icon icon="mdi-content-copy" size="16" />
                </v-btn>
              </div>
            </div>
            <v-menu location="bottom end">
              <template #activator="{ props }">
                <v-btn
                  v-bind="props"
                  icon
                  variant="text"
                  size="small"
                  class="menu-btn"
                  aria-label="User actions"
                >
                  <v-icon icon="mdi-dots-vertical" />
                </v-btn>
              </template>
              <v-list density="compact" min-width="160">
                <v-list-item
                  title="Reset password"
                  prepend-icon="mdi-lock-reset"
                  @click="users.resetPassword(u.id)"
                />
                <v-list-item
                  v-if="u.role !== 'admin'"
                  :title="u.status === 'active' ? 'Disable' : 'Enable'"
                  :prepend-icon="u.status === 'active' ? 'mdi-account-off' : 'mdi-account-check'"
                  @click="users.toggleStatus(u.id)"
                />
              </v-list>
            </v-menu>
          </li>
        </ul>
      </div>
    </div>
  </div>
</template>

<style scoped lang="scss">
.users {
  min-height: 100dvh;
  background: $bg;
}

.bar {
  background: $surface !important;
  border-bottom: 1px solid $stroke;
}

.back-icon {
  transition: transform 0.2s ease;
}
.bar :deep(.v-btn:hover) .back-icon {
  transform: translateX(-3px);
}

.title {
  font-family: 'Space Grotesk', sans-serif !important;
  font-weight: 600 !important;
  font-size: 1.05rem !important;
}

.content {
  padding: 16px;
  max-width: 480px;
  margin: 0 auto;
  display: flex;
  flex-direction: column;
  gap: 14px;
}

.panel {
  padding: 20px 16px;
  background: $surface;
  border: 1px solid $stroke;
  border-radius: $radius;
}

.section {
  margin: 0 0 14px;
  font-family: 'Space Grotesk', sans-serif;
  font-size: 0.95rem;
  font-weight: 600;
  color: $text;
}

.fields {
  display: flex;
  flex-direction: column;
  gap: 12px;
  margin-bottom: 14px;
}

.copy-field {
  position: relative;

  .copy-btn {
    position: absolute;
    right: 8px;
    top: 50%;
    transform: translateY(-50%);
    z-index: 1;
  }
}

.btn-gradient {
  width: 100%;
  height: 44px;
  border: none;
  border-radius: $radius-btn;
  background: $gradient;
  color: #fff;
  font-family: 'Space Grotesk', sans-serif;
  font-weight: 600;
  cursor: pointer;
  transition:
    filter 0.15s,
    transform 0.15s;
  &:active {
    transform: scale(0.98);
  }
  &:hover {
    filter: brightness(1.08);
  }
}

.search {
  margin-bottom: 14px;
}

.list-loader {
  display: flex;
  align-items: center;
  justify-content: center;
  min-height: 72px;
  color: $blue;
}

.list {
  list-style: none;
  margin: 0;
  padding: 0;
  display: flex;
  flex-direction: column;
  gap: 10px;
}

.row {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
  padding: 12px;
  background: $surface-2;
  border-radius: $radius-btn;
}

.info {
  min-width: 0;
  flex: 1;
}

.name {
  margin: 0;
  display: inline-flex;
  align-items: center;
  gap: 4px;
  font-family: 'Space Grotesk', sans-serif;
  font-size: 0.9rem;
  font-weight: 600;
  color: $text;
}

.status-dot {
  display: inline-block;
  width: 8px;
  height: 8px;
  border-radius: 50%;
  background: $red;
  flex-shrink: 0;
}

.admin-star {
  color: $blue;
}

.email-row {
  display: flex;
  align-items: center;
  gap: 2px;
  margin-top: 2px;
}

.email {
  margin: 0;
  font-size: 0.8rem;
  color: $muted;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.menu-btn {
  flex-shrink: 0;
}

:deep(.v-field) {
  border-radius: $radius-btn !important;
  background: $surface-2;
}
</style>
