// gt-frontend-react/src/features/workout/WorkoutPage.jsx
import { useEffect, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import {
  AppBar,
  Toolbar,
  Box,
  IconButton,
  Typography,
  Checkbox,
  Menu,
  MenuItem,
  ListItemIcon,
  ListItemText,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  TextField,
  Button,
  InputAdornment,
} from '@mui/material'
import ArrowBackIcon from '@mui/icons-material/ArrowBack'
import AddIcon from '@mui/icons-material/Add'
import ChevronUpIcon from '@mui/icons-material/KeyboardArrowUp'
import ChevronDownIcon from '@mui/icons-material/KeyboardArrowDown'
import MoreVertIcon from '@mui/icons-material/MoreVert'
import EditOutlinedIcon from '@mui/icons-material/EditOutlined'
import DeleteOutlineIcon from '@mui/icons-material/DeleteOutlined'
import FitnessCenterIcon from '@mui/icons-material/FitnessCenter'
import DirectionsRunIcon from '@mui/icons-material/DirectionsRun'
import ScaleIcon from '@mui/icons-material/Scale'
import NotesIcon from '@mui/icons-material/Notes'
import { useAppDispatch, useAppSelector } from '@/app/hooks'
import { colors } from '@/app/theme'
import { snack } from '@/features/ui/uiSlice'
import {
  loadDraft,
  toggleExercise,
  saveExercise,
  deleteExercise,
  clearDraft,
  selectDraft,
  sanitizeWeight,
} from '@/features/workout/workoutSlice'

const fieldSx = {
  '& .MuiOutlinedInput-root': {
    borderRadius: colors.radiusBtn,
    bgcolor: colors.surface2,
  },
}

function GradientButton({ children, onClick, sx }) {
  return (
    <Box
      component="button"
      type="button"
      onClick={onClick}
      sx={{
        minWidth: 96,
        height: 40,
        px: 2.75,
        border: 'none',
        borderRadius: colors.radiusBtn,
        background: colors.gradient,
        color: '#fff',
        fontFamily: "'Space Grotesk', sans-serif",
        fontWeight: 600,
        cursor: 'pointer',
        '&:active': { transform: 'scale(0.97)' },
        ...sx,
      }}
    >
      {children}
    </Box>
  )
}

export default function WorkoutPage() {
  const { workoutId } = useParams()
  const dispatch = useAppDispatch()
  const navigate = useNavigate()
  const draft = useAppSelector(selectDraft)

  const [expandedId, setExpandedId] = useState(null)
  const [dialogOpen, setDialogOpen] = useState(false)
  const [dialogMode, setDialogMode] = useState('add')
  const [form, setForm] = useState({
    id: null,
    name: '',
    weight: '',
    weightUnit: 'kg',
    description: '',
  })
  const [menuAnchor, setMenuAnchor] = useState(null)
  const [menuExId, setMenuExId] = useState(null)

  useEffect(() => {
    const load = async () => {
      const id = String(workoutId || '')
      setExpandedId(null)
      const result = await dispatch(loadDraft(id))
      if (loadDraft.rejected.match(result)) {
        dispatch(snack.error('Workout not found'))
        navigate('/', { replace: true })
      }
    }
    load()
    return () => dispatch(clearDraft())
  }, [workoutId, dispatch, navigate])

  const goBack = () => {
    dispatch(clearDraft())
    navigate('/')
  }

  const toggleExpand = exId => {
    setExpandedId(prev => (prev === exId ? null : exId))
  }

  const openAdd = () => {
    setDialogMode('add')
    setForm({ id: null, name: '', weight: '', weightUnit: 'kg', description: '' })
    setDialogOpen(true)
  }

  const openEdit = ex => {
    setDialogMode('edit')
    setForm({
      id: ex.id,
      name: ex.name,
      weight: sanitizeWeight(ex.weight),
      weightUnit: ex.weightUnit === 'lb' ? 'lb' : 'kg',
      description: ex.description || '',
    })
    setDialogOpen(true)
  }

  const closeDialog = () => setDialogOpen(false)

  const setWeight = value => {
    setForm(f => ({ ...f, weight: sanitizeWeight(value) }))
  }

  const onWeightKeydown = e => {
    const allow = [
      'Backspace',
      'Delete',
      'Tab',
      'Escape',
      'Enter',
      'ArrowLeft',
      'ArrowRight',
      'ArrowUp',
      'ArrowDown',
      'Home',
      'End',
    ]
    if (allow.includes(e.key)) return
    if ((e.ctrlKey || e.metaKey) && ['a', 'c', 'v', 'x'].includes(e.key.toLowerCase())) return
    if (/^\d$/.test(e.key)) return
    if (e.key === '.' && !String(form.weight ?? '').includes('.')) return
    e.preventDefault()
  }

  const handleSaveExercise = async () => {
    const result = await dispatch(saveExercise({ mode: dialogMode, form }))
    if (saveExercise.fulfilled.match(result)) closeDialog()
  }

  const handleDeleteExercise = async exId => {
    const result = await dispatch(deleteExercise(exId))
    if (deleteExercise.fulfilled.match(result) && expandedId === exId) setExpandedId(null)
  }

  if (!draft || draft.id !== workoutId) return null

  return (
    <Box sx={{ bgcolor: colors.bg, display: 'flex', flexDirection: 'column', minHeight: '100%' }}>
      <AppBar
        position="static"
        elevation={0}
        sx={{ bgcolor: colors.surface, borderBottom: `1px solid ${colors.stroke}`, height: 56 }}
      >
        <Toolbar sx={{ minHeight: '56px !important' }}>
          <IconButton
            aria-label="Back"
            onClick={goBack}
            sx={{
              color: colors.text,
              '&:hover .back-icon': { transform: 'translateX(-3px)' },
            }}
          >
            <ArrowBackIcon className="back-icon" sx={{ transition: 'transform 0.2s' }} />
          </IconButton>
          <Typography
            variant="h6"
            sx={{
              fontFamily: "'Space Grotesk', sans-serif",
              fontWeight: 600,
              fontSize: '1.05rem',
              color: colors.text,
            }}
          >
            {draft.title}
          </Typography>
        </Toolbar>
      </AppBar>

      <Box sx={{ flex: 1, p: '12px 16px', maxWidth: 900, width: '100%', mx: 'auto' }}>
        <Box
          sx={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            gap: 1.5,
            mb: 1.5,
            p: '12px 14px',
            bgcolor: colors.surface,
            border: `1px solid ${colors.stroke}`,
            borderRadius: colors.radius,
          }}
        >
          <Box
            component="span"
            sx={{
              fontFamily: "'Space Grotesk', sans-serif",
              fontSize: '0.85rem',
              fontWeight: 600,
              color: colors.muted,
              textTransform: 'uppercase',
              letterSpacing: '0.04em',
            }}
          >
            Exercises
          </Box>
          <Box
            component="span"
            sx={{
              fontFamily: "'Space Grotesk', sans-serif",
              fontSize: '1.25rem',
              fontWeight: 700,
              color: colors.text,
              fontVariantNumeric: 'tabular-nums',
            }}
          >
            {draft.exercises.length}
          </Box>
        </Box>

        <Box
          sx={{
            bgcolor: colors.surface,
            border: `1px solid ${colors.stroke}`,
            borderRadius: colors.radius,
            overflow: 'hidden',
          }}
        >
          {draft.exercises.length === 0 ? (
            <Box sx={{ p: '48px 20px', textAlign: 'center', color: colors.muted }}>
              <FitnessCenterIcon
                sx={{
                  fontSize: 40,
                  opacity: 0.5,
                  animation: 'float 2.5s ease-in-out infinite',
                  '@keyframes float': {
                    '0%, 100%': { transform: 'translateY(0)' },
                    '50%': { transform: 'translateY(-6px)' },
                  },
                }}
              />
              <Box
                component="p"
                sx={{
                  m: '12px 0 4px',
                  fontFamily: "'Space Grotesk', sans-serif",
                  fontWeight: 600,
                  color: colors.text,
                }}
              >
                No exercises yet
              </Box>
              <Box component="span" sx={{ fontSize: '0.85rem' }}>
                Tap + to get started
              </Box>
            </Box>
          ) : (
            <Box sx={{ width: '100%' }}>
              <Box
                sx={{
                  display: 'grid',
                  gridTemplateColumns: {
                    xs: '40px minmax(0, 1fr) 64px 50px',
                    md: '44px minmax(0, 1fr) 80px 54px',
                  },
                  gap: { xs: 1, md: 1.5 },
                  alignItems: 'center',
                  minHeight: 40,
                  px: { xs: 1.5, md: 1.75 },
                  fontSize: '0.68rem',
                  fontWeight: 600,
                  textTransform: 'uppercase',
                  letterSpacing: '0.05em',
                  color: colors.muted,
                  borderBottom: `1px solid ${colors.stroke}`,
                  bgcolor: colors.surface2,
                }}
              >
                <span aria-hidden="true" />
                <span>Exercise</span>
                <span>Weight</span>
                <Box component="span" sx={{ textAlign: 'right' }}>
                  Actions
                </Box>
              </Box>

              {draft.exercises.map(ex => {
                const open = expandedId === ex.id
                return (
                  <Box
                    key={ex.id}
                    sx={{
                      borderBottom: `1px solid ${colors.stroke}`,
                      '&:last-child': { borderBottom: 'none' },
                      ...(ex.done && {
                        '& .ex-name': { textDecoration: 'line-through', color: colors.muted },
                      }),
                      ...(open && {
                        '& .detail': { borderTop: `1px solid ${colors.stroke}` },
                        '& .chevron': { color: colors.blue },
                      }),
                    }}
                  >
                    <Box
                      role="button"
                      tabIndex={0}
                      onClick={() => toggleExpand(ex.id)}
                      onKeyDown={e => {
                        if (e.key === 'Enter') {
                          e.preventDefault()
                          toggleExpand(ex.id)
                        }
                      }}
                      sx={{
                        display: 'grid',
                        gridTemplateColumns: {
                          xs: '40px minmax(0, 1fr) 64px 50px',
                          md: '44px minmax(0, 1fr) 80px 54px',
                        },
                        gap: { xs: 1, md: 1.5 },
                        alignItems: 'center',
                        minHeight: 52,
                        px: { xs: 1.5, md: 1.75 },
                        cursor: 'pointer',
                        WebkitTapHighlightColor: 'transparent',
                        '&:active': { bgcolor: 'rgba(59, 130, 246, 0.05)' },
                      }}
                    >
                      <Box
                        sx={{ display: 'flex', alignItems: 'center', justifyContent: 'center' }}
                        onClick={e => e.stopPropagation()}
                      >
                        <Checkbox
                          checked={!!ex.done}
                          color="success"
                          size="small"
                          slotProps={{ input: { 'aria-label': 'Mark exercise done' } }}
                          onChange={() => dispatch(toggleExercise(ex.id))}
                        />
                      </Box>
                      <Box
                        sx={{
                          display: 'flex',
                          alignItems: 'center',
                          gap: 0.75,
                          overflow: 'hidden',
                          minWidth: 0,
                        }}
                      >
                        <Box
                          className="ex-name"
                          component="p"
                          sx={{
                            m: 0,
                            flex: 1,
                            minWidth: 0,
                            fontWeight: 600,
                            fontSize: '0.9rem',
                            overflow: 'hidden',
                            textOverflow: 'ellipsis',
                            whiteSpace: 'nowrap',
                            color: colors.text,
                          }}
                        >
                          {ex.name}
                        </Box>
                        {open ? (
                          <ChevronUpIcon
                            className="chevron"
                            sx={{ fontSize: 18, color: colors.muted, flexShrink: 0 }}
                          />
                        ) : (
                          <ChevronDownIcon
                            className="chevron"
                            sx={{ fontSize: 18, color: colors.muted, flexShrink: 0 }}
                          />
                        )}
                      </Box>
                      <Box
                        component="p"
                        sx={{
                          m: 0,
                          fontFamily: "'JetBrains Mono', monospace",
                          fontSize: '0.85rem',
                          fontWeight: 500,
                          color: colors.text,
                          overflow: 'hidden',
                          textOverflow: 'ellipsis',
                          whiteSpace: 'nowrap',
                        }}
                      >
                        {ex.weight ? `${ex.weight} ${ex.weightUnit === 'lb' ? 'lb' : 'kg'}` : '—'}
                      </Box>
                      <Box
                        sx={{
                          display: 'flex',
                          alignItems: 'center',
                          justifyContent: 'flex-end',
                        }}
                        onClick={e => e.stopPropagation()}
                      >
                        <IconButton
                          size="small"
                          aria-label="Exercise actions"
                          sx={{ color: colors.muted }}
                          onClick={e => {
                            setMenuExId(ex.id)
                            setMenuAnchor(e.currentTarget)
                          }}
                        >
                          <MoreVertIcon sx={{ fontSize: 20 }} />
                        </IconButton>
                      </Box>
                    </Box>
                    {open && (
                      <Box
                        className="detail"
                        sx={{
                          p: '10px 14px 14px',
                          bgcolor: colors.surface2,
                          animation: 'expand-in 0.18s ease',
                          '@keyframes expand-in': {
                            from: { opacity: 0, transform: 'translateY(-4px)' },
                            to: { opacity: 1, transform: 'translateY(0)' },
                          },
                        }}
                      >
                        <Box
                          component="p"
                          sx={{
                            m: '0 0 4px',
                            fontSize: '0.68rem',
                            fontWeight: 600,
                            textTransform: 'uppercase',
                            letterSpacing: '0.05em',
                            color: colors.muted,
                          }}
                        >
                          Description
                        </Box>
                        <Box
                          component="p"
                          sx={{
                            m: 0,
                            fontSize: '0.875rem',
                            lineHeight: 1.45,
                            color: colors.text,
                            whiteSpace: 'pre-line',
                          }}
                        >
                          {ex.description || 'No description'}
                        </Box>
                      </Box>
                    )}
                  </Box>
                )
              })}
            </Box>
          )}
        </Box>
      </Box>

      <Menu
        anchorEl={menuAnchor}
        open={Boolean(menuAnchor)}
        onClose={() => {
          setMenuAnchor(null)
          setMenuExId(null)
        }}
        anchorOrigin={{ vertical: 'bottom', horizontal: 'right' }}
        transformOrigin={{ vertical: 'top', horizontal: 'right' }}
        slotProps={{
          paper: {
            sx: { bgcolor: colors.surface2, border: `1px solid ${colors.stroke}` },
          },
        }}
      >
        <MenuItem
          onClick={() => {
            const ex = draft.exercises.find(e => e.id === menuExId)
            setMenuAnchor(null)
            if (ex) openEdit(ex)
          }}
        >
          <ListItemIcon>
            <EditOutlinedIcon fontSize="small" />
          </ListItemIcon>
          <ListItemText>Edit</ListItemText>
        </MenuItem>
        <MenuItem
          sx={{ color: colors.red, '& .MuiListItemIcon-root': { color: colors.red } }}
          onClick={() => {
            const id = menuExId
            setMenuAnchor(null)
            if (id) handleDeleteExercise(id)
          }}
        >
          <ListItemIcon>
            <DeleteOutlineIcon fontSize="small" />
          </ListItemIcon>
          <ListItemText>Delete</ListItemText>
        </MenuItem>
      </Menu>

      <Box
        component="button"
        type="button"
        aria-label="Add exercise"
        onClick={openAdd}
        sx={{
          position: 'fixed',
          right: 20,
          bottom: 'calc(20px + env(safe-area-inset-bottom))',
          zIndex: 20,
          width: 58,
          height: 58,
          border: 'none',
          borderRadius: '50%',
          background: colors.gradient,
          color: '#fff',
          display: 'grid',
          placeItems: 'center',
          boxShadow: '0 8px 24px rgba(59, 130, 246, 0.35)',
          cursor: 'pointer',
          animation: 'fab-in 0.45s cubic-bezier(0.34, 1.56, 0.64, 1)',
          transition: 'transform 0.2s ease',
          '&:hover': { transform: 'scale(1.08) rotate(90deg)' },
          '&:active': { transform: 'scale(0.95)' },
          '@keyframes fab-in': {
            from: { transform: 'scale(0)', opacity: 0 },
            to: { transform: 'scale(1)', opacity: 1 },
          },
        }}
      >
        <AddIcon sx={{ fontSize: 28 }} />
      </Box>

      <Dialog open={dialogOpen} onClose={closeDialog} maxWidth="xs" fullWidth>
        <Box
          sx={{
            bgcolor: colors.surface,
            border: `1px solid ${colors.stroke}`,
            borderRadius: colors.radius,
          }}
        >
          <DialogTitle sx={{ fontFamily: "'Space Grotesk', sans-serif", fontWeight: 600 }}>
            {dialogMode === 'edit' ? 'Edit exercise' : 'Add exercise'}
          </DialogTitle>
          <DialogContent sx={{ display: 'flex', flexDirection: 'column', gap: 1.5 }}>
            <TextField
              label="Name"
              value={form.name}
              onChange={e => setForm(f => ({ ...f, name: e.target.value }))}
              slotProps={{
                input: {
                  startAdornment: (
                    <InputAdornment position="start">
                      <DirectionsRunIcon sx={{ color: colors.muted, fontSize: 20 }} />
                    </InputAdornment>
                  ),
                },
              }}
              sx={fieldSx}
            />
            <Box sx={{ display: 'flex', alignItems: 'flex-start', gap: 1 }}>
              <TextField
                label="Weight"
                value={form.weight}
                onChange={e => setWeight(e.target.value)}
                onKeyDown={onWeightKeydown}
                slotProps={{
                  input: {
                    inputMode: 'decimal',
                    startAdornment: (
                      <InputAdornment position="start">
                        <ScaleIcon sx={{ color: colors.muted, fontSize: 20 }} />
                      </InputAdornment>
                    ),
                  },
                }}
                sx={{ ...fieldSx, flex: 1, minWidth: 0 }}
              />
              <Box
                role="group"
                aria-label="Weight unit"
                sx={{
                  display: 'grid',
                  gridTemplateColumns: '1fr 1fr',
                  gap: 0.75,
                  flexShrink: 0,
                  width: 96,
                  pt: '2px',
                }}
              >
                {['kg', 'lb'].map(unit => (
                  <Box
                    key={unit}
                    component="button"
                    type="button"
                    onClick={() => setForm(f => ({ ...f, weightUnit: unit }))}
                    sx={{
                      height: 40,
                      border: `1px solid ${form.weightUnit === unit ? colors.blue : colors.stroke}`,
                      borderRadius: colors.radiusBtn,
                      bgcolor:
                        form.weightUnit === unit ? 'rgba(59, 130, 246, 0.12)' : colors.surface2,
                      color: form.weightUnit === unit ? colors.text : colors.muted,
                      fontFamily: "'Space Grotesk', sans-serif",
                      fontSize: '0.85rem',
                      fontWeight: 600,
                      cursor: 'pointer',
                      transition: 'border-color 0.15s, color 0.15s, background 0.15s',
                      '&:hover': form.weightUnit !== unit ? { color: colors.text } : {},
                    }}
                  >
                    {unit}
                  </Box>
                ))}
              </Box>
            </Box>
            <TextField
              label="Description"
              value={form.description}
              onChange={e => setForm(f => ({ ...f, description: e.target.value }))}
              multiline
              minRows={3}
              maxRows={6}
              slotProps={{
                input: {
                  startAdornment: (
                    <InputAdornment position="start" sx={{ alignSelf: 'flex-start', mt: 1.5 }}>
                      <NotesIcon sx={{ color: colors.muted, fontSize: 20 }} />
                    </InputAdornment>
                  ),
                },
              }}
              sx={fieldSx}
            />
          </DialogContent>
          <DialogActions sx={{ px: 2, pb: 2, gap: 1 }}>
            <Button
              variant="outlined"
              onClick={closeDialog}
              sx={{ borderColor: colors.stroke, color: colors.muted }}
            >
              Cancel
            </Button>
            <GradientButton onClick={handleSaveExercise}>
              {dialogMode === 'edit' ? 'Update' : 'Add'}
            </GradientButton>
          </DialogActions>
        </Box>
      </Dialog>
    </Box>
  )
}

// gt-frontend/src/pages/workout/WorkoutPage.vue
<script setup>
import { ref, onMounted } from 'vue'
import { onBeforeRouteUpdate, useRoute, useRouter } from 'vue-router'
import { useWorkoutStore } from '@/stores/workout.store'
import { useSnackbarStore } from '@/stores/snackbar.store'

const route = useRoute()
const router = useRouter()
const workout = useWorkoutStore()

const expandedId = ref(null)
const dialogOpen = ref(false)
const dialogMode = ref('add')
const form = ref({ name: '', weight: '', weightUnit: 'kg', description: '' })

function loadFromRoute(workoutId = route.params.workoutId) {
  const id = String(workoutId || '')
  expandedId.value = null
  return workout.loadDraft(id).then(ok => {
    if (!ok) {
      useSnackbarStore().error('Workout not found')
      router.replace({ name: 'dashboard' })
    }
  })
}

onMounted(() => {
  loadFromRoute()
})
onBeforeRouteUpdate(to => {
  return loadFromRoute(to.params.workoutId)
})

function toggleExpand(exId) {
  expandedId.value = expandedId.value === exId ? null : exId
}

function openAdd() {
  dialogMode.value = 'add'
  form.value = { name: '', weight: '', weightUnit: 'kg', description: '' }
  dialogOpen.value = true
}

function openEdit(ex) {
  dialogMode.value = 'edit'
  form.value = {
    ...ex,
    weight: workout.sanitizeWeight(ex.weight),
    weightUnit: ex.weightUnit === 'lb' ? 'lb' : 'kg',
  }
  dialogOpen.value = true
}

function closeDialog() {
  dialogOpen.value = false
}

function setWeight(value) {
  form.value.weight = workout.sanitizeWeight(value)
}

async function saveExercise() {
  if (await workout.saveExercise(dialogMode.value, form.value)) closeDialog()
}

async function deleteExercise(exId) {
  if ((await workout.deleteExercise(exId)) && expandedId.value === exId) {
    expandedId.value = null
  }
}

function onWeightKeydown(e) {
  const allow = [
    'Backspace',
    'Delete',
    'Tab',
    'Escape',
    'Enter',
    'ArrowLeft',
    'ArrowRight',
    'ArrowUp',
    'ArrowDown',
    'Home',
    'End',
  ]
  if (allow.includes(e.key)) return
  if ((e.ctrlKey || e.metaKey) && ['a', 'c', 'v', 'x'].includes(e.key.toLowerCase())) return
  if (/^\d$/.test(e.key)) return
  if (e.key === '.' && !String(form.value.weight ?? '').includes('.')) return
  e.preventDefault()
}
</script>

<template>
  <div v-if="workout.draft" class="workout">
    <v-app-bar flat class="bar" height="56">
      <v-btn icon variant="text" aria-label="Back" @click="workout.goBack()">
        <v-icon icon="mdi-arrow-left" class="back-icon" />
      </v-btn>
      <v-toolbar-title class="title">{{ workout.draft.title }}</v-toolbar-title>
    </v-app-bar>

    <div class="content">
      <div class="count-bar">
        <span class="count-label">Exercises</span>
        <span class="count-value">{{ workout.draft.exercises.length }}</span>
      </div>

      <div class="panel">
        <div v-if="!workout.draft.exercises.length" class="empty">
          <v-icon icon="mdi-weight-lifter" size="40" class="empty-icon" />
          <p>No exercises yet</p>
          <span>Tap + to get started</span>
        </div>

        <div v-else class="table">
          <div class="thead">
            <span aria-hidden="true" />
            <span>Exercise</span>
            <span>Weight</span>
            <span class="actions-h">Actions</span>
          </div>

          <div
            v-for="ex in workout.draft.exercises"
            :key="ex.id"
            class="accordion"
            :class="{ open: expandedId === ex.id, done: ex.done }"
          >
            <div
              class="row"
              role="button"
              tabindex="0"
              @click="toggleExpand(ex.id)"
              @keydown.enter.prevent="toggleExpand(ex.id)"
            >
              <div class="cell check" @click.stop>
                <v-checkbox-btn
                  :model-value="ex.done"
                  color="success"
                  density="compact"
                  aria-label="Mark exercise done"
                  @update:model-value="workout.toggleExercise(ex.id)"
                />
              </div>

              <div class="cell name-wrap">
                <p class="cell name">{{ ex.name }}</p>
                <v-icon
                  :icon="expandedId === ex.id ? 'mdi-chevron-up' : 'mdi-chevron-down'"
                  size="18"
                  class="chevron"
                />
              </div>

              <p class="cell weight">
                {{ ex.weight ? `${ex.weight} ${ex.weightUnit === 'lb' ? 'lb' : 'kg'}` : '—' }}
              </p>

              <div class="cell actions" @click.stop>
                <v-menu location="bottom end">
                  <template #activator="{ props }">
                    <v-btn
                      v-bind="props"
                      icon
                      variant="text"
                      size="small"
                      class="menu-btn"
                      aria-label="Exercise actions"
                    >
                      <v-icon icon="mdi-dots-vertical" size="20" />
                    </v-btn>
                  </template>
                  <v-list density="compact" class="menu-list">
                    <v-list-item
                      prepend-icon="mdi-pencil-outline"
                      title="Edit"
                      @click="openEdit(ex)"
                    />
                    <v-list-item
                      prepend-icon="mdi-delete-outline"
                      title="Delete"
                      class="danger"
                      @click="deleteExercise(ex.id)"
                    />
                  </v-list>
                </v-menu>
              </div>
            </div>

            <div v-show="expandedId === ex.id" class="detail">
              <p class="detail-label">Description</p>
              <p class="detail-text">
                {{ ex.description || 'No description' }}
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>

    <button class="fab" type="button" aria-label="Add exercise" @click="openAdd()">
      <v-icon icon="mdi-plus" size="28" />
    </button>

    <v-dialog
      :model-value="dialogOpen"
      max-width="420"
      @update:model-value="v => !v && closeDialog()"
    >
      <v-card class="dlg-card">
        <v-card-title class="dlg-title">
          {{ dialogMode === 'edit' ? 'Edit exercise' : 'Add exercise' }}
        </v-card-title>
        <v-card-text class="dlg-fields">
          <v-text-field
            v-model="form.name"
            label="Name"
            prepend-inner-icon="mdi-arm-flex"
            rounded="lg"
          />
          <div class="weight-row">
            <v-text-field
              :model-value="form.weight"
              label="Weight"
              type="text"
              inputmode="decimal"
              prepend-inner-icon="mdi-weight"
              rounded="lg"
              hide-details="auto"
              class="weight-field"
              @keydown="onWeightKeydown"
              @update:model-value="setWeight"
            />
            <div class="unit-toggle" role="group" aria-label="Weight unit">
              <button
                type="button"
                class="unit-btn"
                :class="{ active: form.weightUnit === 'kg' }"
                @click="form.weightUnit = 'kg'"
              >
                kg
              </button>
              <button
                type="button"
                class="unit-btn"
                :class="{ active: form.weightUnit === 'lb' }"
                @click="form.weightUnit = 'lb'"
              >
                lb
              </button>
            </div>
          </div>
          <v-textarea
            v-model="form.description"
            label="Description"
            prepend-inner-icon="mdi-text"
            rounded="lg"
            variant="outlined"
            rows="3"
            auto-grow
            max-rows="6"
            hide-details="auto"
          />
        </v-card-text>
        <v-card-actions class="dlg-actions">
          <v-btn variant="outlined" class="btn-ghost" @click="closeDialog()">Cancel</v-btn>
          <button class="btn-gradient" type="button" @click="saveExercise()">
            {{ dialogMode === 'edit' ? 'Update' : 'Add' }}
          </button>
        </v-card-actions>
      </v-card>
    </v-dialog>
  </div>
</template>

<style scoped lang="scss">
.workout {
  background: $bg;
  display: flex;
  flex-direction: column;
}

.bar {
  background: $surface !important;
  border-bottom: 1px solid $stroke;
}

.back-icon {
  transition: transform 0.2s ease;
}
.bar :deep(.v-btn:hover) .back-icon {
  transform: translateX(-3px);
}

.title {
  font-family: 'Space Grotesk', sans-serif !important;
  font-weight: 600 !important;
  font-size: 1.05rem !important;
}

.content {
  flex: 1;
  padding: 12px 16px;
  max-width: 900px;
  width: 100%;
  margin: 0 auto;
}

.count-bar {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
  margin-bottom: 12px;
  padding: 12px 14px;
  background: $surface;
  border: 1px solid $stroke;
  border-radius: $radius;
}

.count-label {
  font-family: 'Space Grotesk', sans-serif;
  font-size: 0.85rem;
  font-weight: 600;
  color: $muted;
  text-transform: uppercase;
  letter-spacing: 0.04em;
}

.count-value {
  font-family: 'Space Grotesk', sans-serif;
  font-size: 1.25rem;
  font-weight: 700;
  color: $text;
  font-variant-numeric: tabular-nums;
}

.panel {
  background: $surface;
  border: 1px solid $stroke;
  border-radius: $radius;
  overflow: hidden;
}

.empty {
  padding: 48px 20px;
  text-align: center;
  color: $muted;

  p {
    margin: 12px 0 4px;
    font-family: 'Space Grotesk', sans-serif;
    font-weight: 600;
    color: $text;
  }
  span {
    font-size: 0.85rem;
  }
}

.empty-icon {
  opacity: 0.5;
  animation: float 2.5s ease-in-out infinite;
}

@keyframes float {
  0%,
  100% {
    transform: translateY(0);
  }
  50% {
    transform: translateY(-6px);
  }
}

.table {
  width: 100%;
}

.thead,
.row {
  display: grid;
  grid-template-columns: 40px minmax(0, 1fr) 64px 50px;
  gap: 8px;
  align-items: center;
  min-height: 52px;
  padding: 0 12px;

  @media (min-width: 700px) {
    grid-template-columns: 44px minmax(0, 1fr) 80px 54px;
    gap: 12px;
    padding: 0 14px;
  }
}

.thead {
  min-height: 40px;
  font-size: 0.68rem;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  color: $muted;
  border-bottom: 1px solid $stroke;
  background: $surface-2;
}

.actions-h {
  text-align: right;
}

.accordion {
  border-bottom: 1px solid $stroke;

  &:last-child {
    border-bottom: none;
  }
  &.done .name {
    text-decoration: line-through;
    color: $muted;
  }
  &.open .detail {
    border-top: 1px solid $stroke;
  }
}

.row {
  cursor: pointer;
  -webkit-tap-highlight-color: transparent;
  &:active {
    background: rgba($blue, 0.05);
  }
}

.cell {
  margin: 0;
  min-width: 0;
  font-size: 0.9rem;
  line-height: 1.3;
  color: $text;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.check,
.actions {
  display: flex;
  align-items: center;
  justify-content: center;
  overflow: visible;
}

.actions {
  justify-content: flex-end;
}

.name-wrap {
  display: flex;
  align-items: center;
  gap: 6px;
  overflow: hidden;
}

.name {
  flex: 1;
  min-width: 0;
  font-weight: 600;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.chevron {
  flex-shrink: 0;
  color: $muted;
  transition: transform 0.2s ease;
}

.accordion.open .chevron {
  color: $blue;
}

.weight {
  font-family: 'JetBrains Mono', monospace;
  font-size: 0.85rem;
  font-weight: 500;
}

.detail {
  padding: 10px 14px 14px 14px;
  background: $surface-2;
  animation: expand-in 0.18s ease;
}

.detail-label {
  margin: 0 0 4px;
  font-size: 0.68rem;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  color: $muted;
}

.detail-text {
  margin: 0;
  font-size: 0.875rem;
  line-height: 1.45;
  color: $text;
  white-space: pre-line;
}

@keyframes expand-in {
  from {
    opacity: 0;
    transform: translateY(-4px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

.menu-btn {
  color: $muted !important;
}

.fab {
  position: fixed;
  right: 20px;
  bottom: calc(20px + env(safe-area-inset-bottom));
  z-index: 20;
  width: 58px;
  height: 58px;
  border: none;
  border-radius: 50%;
  background: $gradient;
  color: #fff;
  display: grid;
  place-items: center;
  box-shadow: 0 8px 24px rgba($blue, 0.35);
  cursor: pointer;
  animation: fab-in 0.45s cubic-bezier(0.34, 1.56, 0.64, 1);
  transition: transform 0.2s ease;

  &:hover {
    transform: scale(1.08) rotate(90deg);
  }
  &:active {
    transform: scale(0.95);
  }
}

@keyframes fab-in {
  from {
    transform: scale(0);
    opacity: 0;
  }
  to {
    transform: scale(1);
    opacity: 1;
  }
}

.menu-list {
  background: $surface-2 !important;
  border: 1px solid $stroke;
}

.danger {
  color: $red !important;
  :deep(.v-icon) {
    color: $red !important;
  }
}

.btn-ghost {
  border-color: $stroke !important;
  color: $muted !important;
  text-transform: none;
}

.btn-gradient {
  min-width: 96px;
  height: 40px;
  padding: 0 22px;
  border: none;
  border-radius: $radius-btn;
  background: $gradient;
  color: #fff;
  font-family: 'Space Grotesk', sans-serif;
  font-weight: 600;
  cursor: pointer;
  &:active {
    transform: scale(0.97);
  }
}

.dlg-card {
  background: $surface !important;
  border: 1px solid $stroke;
  border-radius: $radius !important;
}

.dlg-title {
  font-family: 'Space Grotesk', sans-serif;
  font-weight: 600;
}
.dlg-fields {
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.weight-row {
  display: flex;
  align-items: flex-start;
  gap: 8px;
}

.weight-field {
  flex: 1;
  min-width: 0;
}

.unit-toggle {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 6px;
  flex-shrink: 0;
  width: 96px;
  padding-top: 2px;
}

.unit-btn {
  height: 40px;
  border: 1px solid $stroke;
  border-radius: $radius-btn;
  background: $surface-2;
  color: $muted;
  font-family: 'Space Grotesk', sans-serif;
  font-size: 0.85rem;
  font-weight: 600;
  cursor: pointer;
  transition:
    border-color 0.15s,
    color 0.15s,
    background 0.15s;

  &.active {
    border-color: $blue;
    color: $text;
    background: rgba($blue, 0.12);
  }

  &:hover:not(.active) {
    color: $text;
  }
}

.dlg-actions {
  padding: 8px 16px 16px;
  gap: 8px;
  justify-content: flex-end;
}

:deep(.v-field) {
  border-radius: $radius-btn !important;
  background: $surface-2;
}
</style>
